services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx-nginx
    ports:
      - "8080:80"
    depends_on:
      - backend-api-1
      - backend-api-2

  backend-api-1:
    build:
      context: ./backend
    container_name: backend-api-1
    environment:
      - INSTANCE=backend-api-1
      # opțional dacă folosești sqlite/uploads shared
      # - DB_PATH=/data/app.db
      # - UPLOAD_DIR=/uploads
    # volumes:
    #   - ./data:/data
    #   - ./uploads:/uploads

  backend-api-2:
    build:
      context: ./backend
    container_name: backend-api-2
    environment:
      - INSTANCE=backend-api-2
      # - DB_PATH=/data/app.db
      # - UPLOAD_DIR=/uploads
    # volumes:
    #   - ./data:/data
    #   - ./uploads:/uploads
