services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx-nginx
    ports:
      - "8080:80"
    depends_on:
      - backend-api-1
      - backend-api-2
    networks:
      - app-network
    
  backend-api-1:
    build:
      context: ./backend
    container_name: backend-api-1
    environment:
      - INSTANCE=backend-api-1
      # opțional dacă folosești sqlite/uploads shared
      - DB_PATH=/data/app.db
      - UPLOAD_DIR=/uploads
    volumes:
      - ./data:/data
      - ./uploads:/uploads
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5000/api/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend-api-2:
    build:
      context: ./backend
    container_name: backend-api-2
    environment:
        - INSTANCE=backend-api-2
        # opțional dacă folosești sqlite/uploads shared
        - DB_PATH=/data/app.db
        - UPLOAD_DIR=/uploads
    volumes:
        - ./data:/data
        - ./uploads:/uploads
    networks:
        - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5000/api/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  app-network:
    driver: bridge